use pr1_so1;

CREATE TABLE IF NOT EXISTS ram_historico (
    id_ram INT AUTO_INCREMENT PRIMARY KEY,
    uso INT NOT NULL,
    ip VARCHAR(50) NOT NULL,
    fecha DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS cpu_historico (
    id_cpu INT AUTO_INCREMENT PRIMARY KEY,
    uso INT NOT NULL,
    ip VARCHAR(50) NOT NULL,
    fecha DATETIME NOT NULL
);
  
