use pr1_so1;

CREATE TABLE IF NOT EXISTS ram (
    id_ram INT AUTO_INCREMENT PRIMARY KEY,
    uso INT NOT NULL,
    ip VARCHAR(25) NOT NULL,
);

CREATE TABLE IF NOT EXISTS cpu (
    id_cpu INT AUTO_INCREMENT PRIMARY KEY,
    uso INT NOT NULL,
    ip VARCHAR(25) NOT NULL,
);
  
