apiVersion: v1
kind: Service
metadata:
  name: python-client
  namespace: so1p2
spec:
  selector:
    app: python
  ports:
  - port: 3000
    targetPort: 3000
    name: python-port
  type: LoadBalancer