apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: so1p2
spec:
  selector:
    matchLabels:
      app: python
  replicas: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: allenrovas/apiredis_pr2:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "400m"
        ports:
          - containerPort: 3000
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret-python
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-python
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: secret-python
              key: MYSQL_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: secret-python
              key: MYSQL_DATABASE
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: secret-python
              key: REDIS_HOST
        - name: REDIS_DB
          valueFrom:
            secretKeyRef:
              name: secret-python
              key: REDIS_DB
      imagePullSecrets:
      - name: dockerhubpull