apiVersion: v1
kind: Secret
metadata:
  name: dockerhubpull
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJhdXRoIjogIllXeHNaVzV5YjNaaGN6cEVRVkpXTURKaFp5b3YiCiAgICB9CiAgfSwKICAiY3JlZEhlbHBlcnMiOiB7CiAgICAiZ2NyLmlvIjogImdjbG91ZCIsCiAgICAidXMuZ2NyLmlvIjogImdjbG91ZCIsCiAgICAiZXUuZ2NyLmlvIjogImdjbG91ZCIsCiAgICAiYXNpYS5nY3IuaW8iOiAiZ2Nsb3VkIiwKICAgICJzdGFnaW5nLWs4cy5nY3IuaW8iOiAiZ2Nsb3VkIiwKICAgICJtYXJrZXRwbGFjZS5nY3IuaW8iOiAiZ2Nsb3VkIgogIH0KfQ==
