apiVersion: v1
kind: Secret
metadata:
  name: secret-go
  namespace: so1p2
type: Opaque
data:
  DB_USER : 'cm9vdA==' 
  DB_PASSWORD : 'REFSVjAyYWcqLw==' 
  DB_HOST : 'MzUuMjM3LjIxNS4xMzc=' 
  DB_NAME : 'c28xX3ByMg==' 
