version: '3'

services:
  base:
      image: "mysql"
      container_name: 'MYSQL_Base'
      environment:
        MYSQL_ROOT_PASSWORD: secret
      volumes:
        - base_mysql:/var/lib/mysql      
      ports:
        - "3306:3306"
  backend:
    image: 'app_node'
    container_name: 'backend_node_pr1so1'
    environment:
      SECRET_ACCESS_KEY_COG: 'FFF'
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: MYSQL_Base
      DB_PORT: 3306
      DB_NAME: pr1_so1
    ports:
      - "8000:8000"
    restart: always
  
  frontend:
    image: 'app_react'
    container_name: 'frontend_vmnode_pr1so1'
    ports:
      - '5137:5137'
    restart: always