version: '3'

services:
  base:
      image: "mysql"
      container_name: 'MYSQL_Base_SO1'
      environment:
        MYSQL_ROOT_PASSWORD: secret
      volumes:
        - base_mysql:/var/lib/mysql      
      ports:
        - "3306:3306"
      restart: always
  backend:
    image: "backend_pr1"
    container_name: 'Backend_Node_Pr1'
    environment:
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: MYSQL_Base_SO1
      DB_PORT: 3306
      DB_NAME: pr1_so1
    ports:
      - "8000:8000"
    restart: always
  frontend:
    image: "frontend_pr1"
    container_name: 'Frontend_React_Pr1'
    ports:
      - "5173:5173"
    restart: always
volumes:
  base_mysql: 
  